### ISSUE TITLE
"Cancel" is a reserved system metacommand

### ISSUE THREAD

**Issue by DogeThis** [vboughner/van.memory#1]
https://github.com/vboughner/van.memory/blob/d986399cfe5df8443e8c88b9c1b936ab0df2debc/resources/en/vocab/DeleteConfirmation.vocab.bxb#L20

"Cancel" is a reserved system metacommand
https://bixbydevelopers.com/dev/docs/reference/ref-topics/meta-commands

Though I don't think there is any harm in it being in the vocab, it doesn't actually do anything.

**Comment by vboughner** [comment]
I've removed `Cancel` from the vocab file in the upcoming v1.1.0, thanks!
